### ISSUE TITLE
Using model-generator server side

### ISSUE THREAD

**Issue by simonseo** [JesungKoo/glb2usdz#1]
Hi @JesungKoo, thanks for the awesome project.

I believe the logic inside `table.ejs` should be moved to a separate module that runs server-side, should you wish to download the model and convert it to a usdz file.

Thanks!

**Comment by JesungKoo** [comment]
Thanks for your attention to the project. Server-side downloading is not available yet, but I'm working on it. If you have any suggestions in implementation, feel free to make a PR :)

**Comment by simonseo** [comment]
Resolved by: https://github.com/JesungKoo/glb2usdz/commit/539aeffbc2a59f0d9ad557b8a79b23d53acd5b8a
